### ISSUE TITLE
gjstest.internal.browser.addToLog spams browser console

### ISSUE THREAD

**Issue by tjgq** [google/gjstest#10]
This line:

https://github.com/google/gjstest/blob/1423e010dd0db5ca35447bb49d894bce53bc51c9/gjstest/internal/js/browser/run_tests.js#L197

spams the browser console while running tests. Can we get rid of it?

**Comment by jacobsa** [comment]
I believe @okdave wrote that line; I'm not sure why.

**Comment by okdave** [comment]
:+1: 
It's probably left over debugging as I was implementing the feature. I'm surprised it's lasted this long. Kill it with fire.
